//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assign1006.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SPOT()
        {
            this.FOOD = new HashSet<FOOD>();
        }
    
        public int Id { get; set; }
        public string spotname { get; set; }
        public string spotcalorie { get; set; }
        public string spotdesc { get; set; }
        public int PLANId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOOD> FOOD { get; set; }
    }
}
